version: "3.7"
services:
  flood-vfs-service:
    image: flood-vfs-service:latest
    depends_on:
      - cf.access-proxy
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - ENDPOINT=${ENDPOINT}
      - POLL_INTERVAL=${POLL_INTERVAL}
      - RCLONE_REMOTE=${RCLONE_REMOTE}
      - MOUNT_DIRECTORY=${MOUNT_DIRECTORY}
  cf.access-proxy:
    image: index.docker.io/tcbrooks/reverse-proxy:latest
    hostname: cf.access-proxy
    ports:
      - "15141:80"
    environment:
      - CFAccess__ClientId=${CF_CLIENT_ID}
      - CFAccess__ClientSecret=${CF_CLIENT_SECRET}
      - CFAccess__Domain=${CF_DOMAINS}
